<a href="https://colab.research.google.com/github/rutujasarode14/Simple_Python_Progarms/blob/main/DS_E_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# Create a new 3x3 square matrix
matrix_c = np.array([
    [2, 1, 3],
    [0, 4, 1],
    [5, 2, 0]
])

print("New 3x3 Matrix:")
print(matrix_c)

# Compute the determinant of the matrix
determinant_c = np.linalg.det(matrix_c)

print("\nDeterminant of the matrix:", determinant_c)

New 3x3 Matrix:
[[2 1 3]
 [0 4 1]
 [5 2 0]]

Determinant of the matrix: -58.999999999999964


In [5]:
import numpy as np

# Define the coefficient matrix A
A = np.array([
    [2, 3],
    [4, 5]
])

# Define the constant vector B
B = np.array([
    [10],
    [20]
])

print("Coefficient Matrix A:")
print(A)
print("\nConstant Vector B:")
print(B)

# Solve the system of linear equations Ax = B
solution_xy = np.linalg.solve(A, B)

print("\nSolution for x and y:")
print(f"x = {solution_xy[0][0]:.2f}")
print(f"y = {solution_xy[1][0]:.2f}")

Coefficient Matrix A:
[[2 3]
 [4 5]]

Constant Vector B:
[[10]
 [20]]

Solution for x and y:
x = 5.00
y = 0.00


In [6]:
import numpy as np

# Define a 3x3 matrix for which we want to find the inverse
# It's important to choose a non-singular matrix (determinant != 0) for an inverse to exist.
matrix_d = np.array([
    [1, 2, 3],
    [0, 1, 4],
    [5, 6, 0]
])

print("Original 3x3 Matrix:")
print(matrix_d)

# Compute the inverse of the matrix
# numpy.linalg.inv() will raise an error if the matrix is singular.
try:
    inverse_matrix_d = np.linalg.inv(matrix_d)
    print("\nInverse of the matrix:")
    print(inverse_matrix_d)
except np.linalg.LinAlgError:
    print("\nError: The matrix is singular and does not have an inverse.")

Original 3x3 Matrix:
[[1 2 3]
 [0 1 4]
 [5 6 0]]

Inverse of the matrix:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
